// Envelope — core wrapper type and construction utilities
export {
  buildEnvelope,
  generateUUIDv7,
  type EventEnvelope,
} from "./envelope.js";

// Inventory events
export {
  INVENTORY_ADJUSTED,
  INVENTORY_COUNTED,
  INVENTORY_TRANSFERRED,
  INVENTORY_RESERVED,
  INVENTORY_RELEASED,
  inventoryAdjusted,
  inventoryCounted,
  inventoryTransferred,
  inventoryReserved,
  inventoryReleased,
  type InventoryAdjustedPayload,
  type InventoryCountedPayload,
  type InventoryTransferredPayload,
  type InventoryReservedPayload,
  type InventoryReleasedPayload,
} from "./inventory.js";

// Register, sales, payments, catalog, and settings events
export {
  REGISTER_SESSION_OPENED,
  REGISTER_SESSION_CLOSED,
  CASH_DROP_RECORDED,
  MANAGER_OVERRIDE_APPROVED,
  SALE_COMPLETED,
  SALE_VOIDED,
  REFUND_ISSUED,
  PAYMENT_CAPTURED,
  PAYMENT_FAILED,
  PRODUCT_CREATED,
  PRODUCT_UPDATED,
  PRODUCT_ARCHIVED,
  VARIANT_CREATED,
  VARIANT_UPDATED,
  TAX_RULE_CREATED,
  TAX_RULE_UPDATED,
  MERCHANT_SETTINGS_UPDATED,
  registerSessionOpened,
  registerSessionClosed,
  cashDropRecorded,
  managerOverrideApproved,
  saleCompleted,
  saleVoided,
  refundIssued,
  paymentCaptured,
  paymentFailed,
  productCreated,
  productUpdated,
  productArchived,
  variantCreated,
  variantUpdated,
  taxRuleCreated,
  taxRuleUpdated,
  merchantSettingsUpdated,
  type RegisterSessionOpenedPayload,
  type RegisterSessionClosedPayload,
  type CashDropRecordedPayload,
  type ManagerOverrideApprovedPayload,
  type SaleCompletedPayload,
  type SaleVoidedPayload,
  type RefundIssuedPayload,
  type PaymentCapturedPayload,
  type PaymentFailedPayload,
  type ProductCreatedPayload,
  type ProductUpdatedPayload,
  type ProductArchivedPayload,
  type VariantCreatedPayload,
  type VariantUpdatedPayload,
  type TaxRuleCreatedPayload,
  type TaxRuleUpdatedPayload,
  type MerchantSettingsUpdatedPayload,
} from "./register.js";
